In [2]:
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt

np.random.seed(0)

In [3]:
def numerical_derivative(f, x):
        delta_x = 1e-4 # 0.0001
        grad = np.zeros_like(x)
    
        it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
        while not it.finished:
            idx = it.multi_index        
            tmp_val = x[idx]
            x[idx] = float(tmp_val) + delta_x
            fx1 = f(x) # f(x+delta_x)
        
            x[idx] = float(tmp_val) - delta_x 
            fx2 = f(x) # f(x-delta_x)
            grad[idx] = (fx1 - fx2) / (2*delta_x)
        
            x[idx] = tmp_val 
            it.iternext()   
        
        return grad

In [4]:
class LinearRegressionTest:
    def __init__(self, x_data, t_data, learning_rate, iteration_count):
        
        # 가중치 W 형상을 자동으로 구하기 위해 입력데이터가 vector 인지,
        # 아니면 matrix 인지 체크 후, 
        # self.xdata 는 무조건 matrix 로 만들어 주면 코드 일관성이 있음
        if x_data.ndim == 1:    # vector
            self.x_data = x_data.reshape(len(x_data), 1)
            self.t_data = t_data.reshape(len(t_data), 1)
        elif x_data.ndim == 2:  # matrix
            self.x_data = x_data
            self.t_data = t_data
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.x_data.shape[1], 1)
        self.b = np.random.rand(1)
        
        self.loss_val_list = []
        
        print("LinearRegressionTest Object is created.\n")
        
    def get_W_b(self):
        return self.W, self.b
        
    def __loss_func(self):
        y = np.dot(self.x_data, self.W) + self.b
    
        return (np.sum((self.t_data - y)**2)) / (len(self.x_data))
    
    # 손실함수 값 계산 함수
    # 입력변수 x, t : numpy type
    def __loss_val(self):
        y = np.dot(self.x_data, self.W) + self.b
    
        return (np.sum((self.t_data - y)**2)) / (len(self.x_data))

    def train(self):
        f = lambda x : self.__loss_func()
        
        print("Initial error value = ", self.__loss_val() , "\n", "Initial W = ", self.W, "\n", ", b = ", self.b )

        start_time = datetime.now()

        for step in range(self.iteration_count):
            self.W -= self.learning_rate * numerical_derivative(f, self.W)
            self.b -= self.learning_rate * numerical_derivative(f, self.b)
            
            if step % (int)(0.05*self.iteration_count) == 0:
                print("step = ", step, "loss value = ", self.__loss_val())
                self.loss_val_list.append(self.__loss_val())
        
        end_time = datetime.now()

        print("")
        print("Elapsed Time => ", end_time - start_time)
        
    def display_lossval_trend(self):
        plt.title('Loss Value Trend')
        plt.xlabel('epochs ( X 1000)')
        plt.ylabel('loss value')
        plt.grid()

        plt.plot(self.loss_val_list, ls='--', lw=2, label='lr={}, epoch={}'.format(self.learning_rate, self.iteration_count))
        plt.legend(loc='best')

        plt.show()
    
    # 학습을 마친 후, 임의의 데이터에 대해 미래 값 예측 함수
    # 입력변수 x : numpy type
    def predict(self, test_data):
        y = np.dot(test_data, self.W) + self.b
    
        return y

In [5]:
try:
    loaded_data = np.loadtxt('./삼대중량_인공지능_데이터.csv', delimiter=',', dtype=np.float32)

    print("loaded_data.shape : ", loaded_data.shape, ", loaded_data : ", loaded_data)

    x_data = loaded_data[ : , 1:-1]
    t_data = loaded_data[ : , [-1]]

    print("x_data.shape : ", x_data.shape)
    print("x_data : ", x_data)
    print("t_data.shape : ", t_data.shape)
    print("t_data : ", t_data)
    
except Exception as err:
    print(str(err))

loaded_data.shape :  (9, 5) , loaded_data :  [[ 70.   80.  100.  100.   35. ]
 [ 76.   95.   90.  120.   37. ]
 [ 78.   80.  150.  160.   38.4]
 [108.  200.  280.  240.   53. ]
 [ 86.   85.  160.  150.   41.7]
 [ 72.  110.  205.  200.   38. ]
 [120.   50.  100.  110.   49. ]
 [ 70.  120.  150.  140.   37. ]
 [ 70.   85.  105.  110.   37. ]]
x_data.shape :  (9, 3)
x_data :  [[ 80. 100. 100.]
 [ 95.  90. 120.]
 [ 80. 150. 160.]
 [200. 280. 240.]
 [ 85. 160. 150.]
 [110. 205. 200.]
 [ 50. 100. 110.]
 [120. 150. 140.]
 [ 85. 105. 110.]]
t_data.shape :  (9, 1)
t_data :  [[35. ]
 [37. ]
 [38.4]
 [53. ]
 [41.7]
 [38. ]
 [49. ]
 [37. ]
 [37. ]]


In [6]:
obj1 = LinearRegressionTest(x_data, t_data, 1e-4, 20001)
obj1.train()

LinearRegressionTest Object is created.

Initial error value =  51426.968020891836 
 Initial W =  [[0.5488135 ]
 [0.71518937]
 [0.60276338]] 
 , b =  [0.54488318]
step =  0 loss value =  6320210.787029945
step =  1000 loss value =  1.78096028753624e+31
step =  2000 loss value =  1.78096028753624e+31
step =  3000 loss value =  1.78096028753624e+31
step =  4000 loss value =  1.78096028753624e+31
step =  5000 loss value =  1.78096028753624e+31
step =  6000 loss value =  1.78096028753624e+31
step =  7000 loss value =  1.78096028753624e+31
step =  8000 loss value =  1.78096028753624e+31
step =  9000 loss value =  1.78096028753624e+31
step =  10000 loss value =  1.78096028753624e+31
step =  11000 loss value =  1.78096028753624e+31
step =  12000 loss value =  1.78096028753624e+31
step =  13000 loss value =  1.78096028753624e+31
step =  14000 loss value =  1.78096028753624e+31
step =  15000 loss value =  1.78096028753624e+31
step =  16000 loss value =  1.78096028753624e+31
step =  17000 loss v

In [9]:
obj2 = LinearRegressionTest(x_data, t_data, 1e-10, 20001)
obj2.train()

LinearRegressionTest Object is created.

Initial error value =  32687.145442520145 
 Initial W =  [[0.56804456]
 [0.92559664]
 [0.07103606]] 
 , b =  [0.0871293]
step =  0 loss value =  32686.361936366025
step =  1000 loss value =  31912.27216711592
step =  2000 loss value =  31156.695619673803
step =  3000 loss value =  30419.189518589395
step =  4000 loss value =  29699.321678147637
step =  5000 loss value =  28996.67024909727
step =  6000 loss value =  28310.8234714363
step =  7000 loss value =  27641.37943311022
step =  8000 loss value =  26987.94583448211
step =  9000 loss value =  26350.139758434067
step =  10000 loss value =  25727.587445968853
step =  11000 loss value =  25119.924077177795
step =  12000 loss value =  24526.79355744682
step =  13000 loss value =  23947.84830877598
step =  14000 loss value =  23382.749066090342
step =  15000 loss value =  22831.16467842194
step =  16000 loss value =  22292.771914846733
step =  17000 loss value =  21767.25527506351
step =  18000 l

In [10]:
obj3 = LinearRegressionTest(x_data, t_data, 1e-2, 20001)
obj3.train()

LinearRegressionTest Object is created.

Initial error value =  46865.03790474517 
 Initial W =  [[0.0202184 ]
 [0.83261985]
 [0.77815675]] 
 , b =  [0.87001215]
step =  0 loss value =  65848056518.07138
step =  1000 loss value =  1.927769226191715e+29
step =  2000 loss value =  1.927769226191715e+29
step =  3000 loss value =  1.927769226191715e+29
step =  4000 loss value =  1.927769226191715e+29
step =  5000 loss value =  1.927769226191715e+29
step =  6000 loss value =  1.927769226191715e+29
step =  7000 loss value =  1.927769226191715e+29
step =  8000 loss value =  1.927769226191715e+29
step =  9000 loss value =  1.927769226191715e+29
step =  10000 loss value =  1.927769226191715e+29
step =  11000 loss value =  1.927769226191715e+29
step =  12000 loss value =  1.927769226191715e+29
step =  13000 loss value =  1.927769226191715e+29
step =  14000 loss value =  1.927769226191715e+29
step =  15000 loss value =  1.927769226191715e+29
step =  16000 loss value =  1.927769226191715e+29
step 

In [11]:
obj4 = LinearRegressionTest(x_data, t_data, 1e-4, 20001)
obj4.train()

LinearRegressionTest Object is created.

Initial error value =  70115.06037885306 
 Initial W =  [[0.97861834]
 [0.79915856]
 [0.46147936]] 
 , b =  [0.78052918]
step =  0 loss value =  8605353.967091782
step =  1000 loss value =  6.113370284270676e+29
step =  2000 loss value =  6.113370284270676e+29
step =  3000 loss value =  6.113370284270676e+29
step =  4000 loss value =  6.113370284270676e+29
step =  5000 loss value =  6.113370284270676e+29
step =  6000 loss value =  6.113370284270676e+29
step =  7000 loss value =  6.113370284270676e+29
step =  8000 loss value =  6.113370284270676e+29
step =  9000 loss value =  6.113370284270676e+29
step =  10000 loss value =  6.113370284270676e+29
step =  11000 loss value =  6.113370284270676e+29
step =  12000 loss value =  6.113370284270676e+29
step =  13000 loss value =  6.113370284270676e+29
step =  14000 loss value =  6.113370284270676e+29
step =  15000 loss value =  6.113370284270676e+29
step =  16000 loss value =  6.113370284270676e+29
step 

In [12]:
obj5 = LinearRegressionTest(x_data, t_data, 1e-5, 20001)
obj5.train()

LinearRegressionTest Object is created.

Initial error value =  9845.153775077466 
 Initial W =  [[0.11827443]
 [0.63992102]
 [0.14335329]] 
 , b =  [0.94466892]
step =  0 loss value =  623.8475064480772
step =  1000 loss value =  70.693849234193
step =  2000 loss value =  70.18563208034439
step =  3000 loss value =  70.11099217201064
step =  4000 loss value =  70.0379585756484
step =  5000 loss value =  69.96504224974893
step =  6000 loss value =  69.89223791367772
step =  7000 loss value =  69.81954537931956
step =  8000 loss value =  69.74696447501611
step =  9000 loss value =  69.674495029348
step =  10000 loss value =  69.60213687115427
step =  11000 loss value =  69.52988982953688
step =  12000 loss value =  69.45775373386003
step =  13000 loss value =  69.38572841374997
step =  14000 loss value =  69.31381369909437
step =  15000 loss value =  69.24200942004244
step =  16000 loss value =  69.17031540700401
step =  17000 loss value =  69.09873149064964
step =  18000 loss value =  

In [13]:
obj3 = LinearRegressionTest(x_data, t_data, 1e-6, 20001)
obj3.train()

LinearRegressionTest Object is created.

Initial error value =  15513.642618618993 
 Initial W =  [[0.52184832]
 [0.41466194]
 [0.26455561]] 
 , b =  [0.77423369]
step =  0 loss value =  12026.86312040616
step =  1000 loss value =  116.10542158770951
step =  2000 loss value =  92.54533548652282
step =  3000 loss value =  82.25977067538413
step =  4000 loss value =  77.10069327826552
step =  5000 loss value =  74.31974549144948
step =  6000 loss value =  72.7712676012979
step =  7000 loss value =  71.89644875275134
step =  8000 loss value =  71.39829470146138
step =  9000 loss value =  71.11268352665512
step =  10000 loss value =  70.94743960951281
step =  11000 loss value =  70.85045872365572
step =  12000 loss value =  70.79221292455661
step =  13000 loss value =  70.75595184193561
step =  14000 loss value =  70.73216978924636
step =  15000 loss value =  70.71547156218182
step =  16000 loss value =  70.70279479047753
step =  17000 loss value =  70.69240120364502
step =  18000 loss val