In [1]:
from google.colab import drive   # colab 사용시 mount 하기 위한 용도. local 에서는 불필요

drive.mount('/content/gdrive/')  # colab 사용시 mount 하기 위한 용도. local 에서는 불필요

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [2]:
%tensorflow_version 1.x

import tensorflow as tf
import numpy as np
from datetime import datetime
import os

working_dir = 'tensorflow_2.x_working_dir'

colab_default_dir = '/content/gdrive/My Drive/Colab Notebooks/'

original_dir = os.getcwd()

try:

  os.chdir(colab_default_dir)

  if not os.path.exists(working_dir):
    os.mkdir(working_dir)

  os.chdir(working_dir)
  print("current dir = ", os.getcwd())

except Exception as err:
  
  os.chdir(original_dir)
  print(str(err))

TensorFlow 1.x selected.
current dir =  /content/gdrive/My Drive/Colab Notebooks/tensorflow_2.x_working_dir


In [3]:
try:
    data = np.loadtxt('./삼대중량_인공지능_데이터.csv', delimiter=',')
    
    print("data.shape = ", data.shape, ", data.ndim = ", data.ndim)
    print(data)
    
except Exception as err:
    print(str(err))

data.shape =  (9, 5) , data.ndim =  2
[[ 70.   80.  100.  100.   35. ]
 [ 76.   95.   90.  120.   37. ]
 [ 78.   80.  150.  160.   38.4]
 [108.  200.  280.  240.   53. ]
 [ 86.   85.  160.  150.   41.7]
 [ 72.  110.  205.  200.   38. ]
 [120.   50.  100.  110.   49. ]
 [ 70.  120.  150.  140.   37. ]
 [ 70.   85.  105.  110.   37. ]]


In [4]:
xdata = data[ :  , 1:-1]
tdata = data[ :  , [-1]]

print("xdata.shape = ", xdata.shape, ", xdata.ndim = ", xdata.ndim)
print("tdata.shape = ", tdata.shape, ", tdata.ndim = ", tdata.ndim)

print("xdata = ", xdata)
print("tdata = ", tdata)

xdata.shape =  (9, 3) , xdata.ndim =  2
tdata.shape =  (9, 1) , tdata.ndim =  2
xdata =  [[ 80. 100. 100.]
 [ 95.  90. 120.]
 [ 80. 150. 160.]
 [200. 280. 240.]
 [ 85. 160. 150.]
 [110. 205. 200.]
 [ 50. 100. 110.]
 [120. 150. 140.]
 [ 85. 105. 110.]]
tdata =  [[35. ]
 [37. ]
 [38.4]
 [53. ]
 [41.7]
 [38. ]
 [49. ]
 [37. ]
 [37. ]]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
T = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3, 1]))
b = tf.Variable(tf.random_normal([1]))

In [6]:
y = tf.matmul(X, W) + b

loss = tf.reduce_mean(tf.square(T - y))

In [7]:
learning_rate = 1e-2

optimizer = tf.train.AdamOptimizer(learning_rate)

train = optimizer.minimize(loss)

In [8]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
    
  start_time = datetime.now()
    
  for step in range(80001):
    loss_val, _ = sess.run([loss, train], feed_dict={X: xdata, T: tdata})
        
    if step % 2000 == 0:
      print("step = ", step, ", loss_val = ", loss_val)
            
  end_time = datetime.now()

  print("")
  print("Elapsed Time => ", end_time - start_time)

step =  0 , loss_val =  21141.18
step =  2000 , loss_val =  67.63287
step =  4000 , loss_val =  52.91093
step =  6000 , loss_val =  34.691547
step =  8000 , loss_val =  24.40692
step =  10000 , loss_val =  22.580853
step =  12000 , loss_val =  22.555489
step =  14000 , loss_val =  22.555489
step =  16000 , loss_val =  22.555494
step =  18000 , loss_val =  22.555489
step =  20000 , loss_val =  22.555487
step =  22000 , loss_val =  22.55552
step =  24000 , loss_val =  22.55548
step =  26000 , loss_val =  22.561432
step =  28000 , loss_val =  22.555485
step =  30000 , loss_val =  22.555498
step =  32000 , loss_val =  22.555475
step =  34000 , loss_val =  22.55549
step =  36000 , loss_val =  22.55561
step =  38000 , loss_val =  22.555487
step =  40000 , loss_val =  22.55725
step =  42000 , loss_val =  22.555489
step =  44000 , loss_val =  22.55549
step =  46000 , loss_val =  22.555487
step =  48000 , loss_val =  22.555477
step =  50000 , loss_val =  23.124731
step =  52000 , loss_val =  22