In [1]:
from google.colab import drive   # colab 사용시 mount 하기 위한 용도. local 에서는 불필요

drive.mount('/content/gdrive/')  # colab 사용시 mount 하기 위한 용도. local 에서는 불필요

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [2]:
%tensorflow_version 1.x

import tensorflow as tf
import numpy as np
from datetime import datetime
import os

working_dir = 'DSC_project'

colab_default_dir = '/content/gdrive/My Drive/Colab Notebooks/'

original_dir = os.getcwd()

try:

  os.chdir(colab_default_dir)

  if not os.path.exists(working_dir):
    os.mkdir(working_dir)

  os.chdir(working_dir)
  print("current dir = ", os.getcwd())

except Exception as err:
  
  os.chdir(original_dir)
  print(str(err))

TensorFlow 1.x selected.
current dir =  /content/gdrive/My Drive/Colab Notebooks/DSC_project


In [3]:
try:
    data = np.loadtxt('./삼대중량_인공지능_데이터(14).csv', delimiter=',')
    
    print("data.shape = ", data.shape, ", data.ndim = ", data.ndim)
    print(data)
    
except Exception as err:
    print(str(err))

data.shape =  (14, 5) , data.ndim =  2
[[ 70.   80.  100.  100.   35. ]
 [ 76.   95.   90.  120.   37. ]
 [ 78.   80.  150.  160.   38.4]
 [ 86.   85.  160.  150.   41.7]
 [ 72.  110.  205.  200.   38. ]
 [120.   50.  100.  110.   49. ]
 [ 70.  120.  150.  140.   37. ]
 [ 70.   85.  105.  110.   37. ]
 [ 90.   90.  120.  100.   34.2]
 [120.   70.  110.   85.   34.2]
 [ 75.  115.  200.  175.   40. ]
 [ 70.   80.  130.  100.   40. ]
 [ 62.   80.  120.  110.   31. ]
 [ 72.  100.  190.  200.   39. ]]


In [4]:
xdata = data[ :  , 1:-1]
tdata = data[ :  , [-1]]

print("xdata.shape = ", xdata.shape, ", xdata.ndim = ", xdata.ndim)
print("tdata.shape = ", tdata.shape, ", tdata.ndim = ", tdata.ndim)

print("xdata = ", xdata)
print("tdata = ", tdata)

xdata.shape =  (14, 3) , xdata.ndim =  2
tdata.shape =  (14, 1) , tdata.ndim =  2
xdata =  [[ 80. 100. 100.]
 [ 95.  90. 120.]
 [ 80. 150. 160.]
 [ 85. 160. 150.]
 [110. 205. 200.]
 [ 50. 100. 110.]
 [120. 150. 140.]
 [ 85. 105. 110.]
 [ 90. 120. 100.]
 [ 70. 110.  85.]
 [115. 200. 175.]
 [ 80. 130. 100.]
 [ 80. 120. 110.]
 [100. 190. 200.]]
tdata =  [[35. ]
 [37. ]
 [38.4]
 [41.7]
 [38. ]
 [49. ]
 [37. ]
 [37. ]
 [34.2]
 [34.2]
 [40. ]
 [40. ]
 [31. ]
 [39. ]]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
T = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([3, 1]))
b = tf.Variable(tf.random_normal([1]))

In [6]:
y = tf.matmul(X, W) + b

loss = tf.reduce_mean(tf.square(T - y))

In [7]:
learning_rate = 1e-1

optimizer = tf.train.AdamOptimizer(learning_rate)

train = optimizer.minimize(loss)

In [35]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
    
  start_time = datetime.now()
    
  for step in range(10001):
    loss_val, _ = sess.run([loss, train], feed_dict={X: xdata, T: tdata})
        
    if step % 1000 == 0:
      print("step = ", step, ", loss_val = ", loss_val)
            
  end_time = datetime.now()

  print("")
  print("Elapsed Time => ", end_time - start_time)

  print("\nW = ", sess.run(W))
  print("b = ", sess.run(b))

  predict_val = sess.run(y, feed_dict={X: [[70., 100., 80.]]})

  print("\npredict_val = ", predict_val)

step =  0 , loss_val =  497.91705
step =  1000 , loss_val =  12.948968
step =  2000 , loss_val =  11.155046
step =  3000 , loss_val =  11.007563
step =  4000 , loss_val =  11.007233
step =  5000 , loss_val =  11.007888
step =  6000 , loss_val =  62.2811
step =  7000 , loss_val =  11.007204
step =  8000 , loss_val =  11.050422
step =  9000 , loss_val =  17.83333
step =  10000 , loss_val =  11.007202

Elapsed Time =>  0:00:10.275576

W =  [[-0.15523091]
 [-0.00016594]
 [ 0.07290757]]
b =  [42.04991]

predict_val =  [[36.99976]]


RuntimeError: ignored